#include "UnityCG.cginc"
#include "../Shaders/LitboxCommon.cginc"
#pragma kernel CloudForegroundBlur

Texture2D<float4> blur_input;
SamplerState samplerblur_input;
Texture2D<float4> density;
SamplerState samplerdensity;
RWTexture2D<float4> blur_output;
Texture2D<float4> kernel_lut;

float4 kernel_sample_points[256];
float kernel_weights[256];
int kernel_sample_count;
float2 sample_offset;
float2 sample_increment;
int lod;
float transmission_depth;

[numthreads(16,16,1)]
void CloudForegroundBlur (uint3 id : SV_DispatchThreadID) {
    float2 uv = (id.xy + 0.5) / TextureSize(blur_output) + sample_offset;
    float3 result = float3(0,0,0);
    float a = 0;

    for(int i = 0;i < kernel_sample_count;i++) {
        float2 sample_uv = uv + i * sample_increment;
        float weight = kernel_weights[i];
        a += weight;
        float t = 1 - density.SampleLevel(samplerdensity, sample_uv, 0).x / DENSITY_SCALE;
        result += blur_input.SampleLevel(samplerblur_input, sample_uv, lod).rgb * weight;// * pow(t, transmission_depth);
    }   

    blur_output[id.xy] = float4(result / a, 1.0);
}