#include "UnityCG.cginc"
#include "../Shaders/LitboxCommon.cginc"

#pragma kernel CSMain

Texture2D<float3> radiance;
Texture2D<float> variance;
Texture2D<float3> albedo;
Texture2D<float> transmissibility;

RWStructuredBuffer<float> output;

uint2 size;
uint stride;

[numthreads(16, 16, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (any(id >= size)) return;

    uint pixelIndex = id.y * size.x + id.x;

    output[pixelIndex + 0 * stride] = radiance[id.xy].r;
    output[pixelIndex + 1 * stride] = radiance[id.xy].g;
    output[pixelIndex + 2 * stride] = radiance[id.xy].b;
    output[pixelIndex + 3 * stride] = variance[id.xy];
    output[pixelIndex + 4 * stride] = albedo[id.xy].r;
    output[pixelIndex + 5 * stride] = albedo[id.xy].g;
    output[pixelIndex + 6 * stride] = albedo[id.xy].b;
    output[pixelIndex + 7 * stride] = transmissibility[id.xy];
}