#include "../Shaders/LitboxCommon.cginc"

#pragma kernel MakeDensityTensor
#pragma kernel MakePhotonCountTensor

Texture2D<float4> in_density;
Texture2D<uint> in_photon_count;

RWTexture2D<float4> out_density;
[numthreads(8,8,1)]
void MakeDensityTensor(uint3 id : SV_DispatchThreadID) {
    out_density[id.xy] = float4(in_density[id.xy].x, 0, 0, 1) / DENSITY_SCALE;
}

RWTexture2D<float4> out_photon_count;
[numthreads(8,8,1)]
void MakePhotonCountTensor(uint3 id : SV_DispatchThreadID) {
    out_photon_count[id.xy] = float4(in_photon_count[id.xy].x, 0, 0, 1);
}